export { boardsService, boardStagesService } from './boards'
export { contactsService, companiesService } from './contacts'
export { dealsService } from './deals'
export { activitiesService } from './activities'
export { productsService } from './products'
export { settingsService, lifecycleStagesService } from './settings'
export { dealNotesService } from './dealNotes'
export { dealFilesService } from './dealFiles'
export { quickScriptsService } from './quickScripts'
export { aiSuggestionsService } from './aiSuggestions'
export { apiKeysService } from './apiKeys'
export { auditService } from './audit'
export { dashboardService } from './dashboard'
export { requireAuth, requireAdmin, getCurrentOrganizationId } from './auth-check'
export * from './consent'
